### ISSUE TITLE
Issue calling watch-history file?

### ISSUE THREAD

**Issue by ghost** [Jessime/youtube_history#14]
Hi Jessime,

I'm working on a personal project involving analysis of youtube user data and came across your Github project about Youtube History Analysis. It's been very helpful so thanks for making it public. I'm emailing because I keep getting the same error in my terminal and I'm not sure what the issue is:

`zawwarnaseer@apples-MBP youtube_history-master %  python youtube_history.py --takeout YouTube_and_YouTube_Music/history/watch-history.html
Welcome!
Traceback (most recent call last):
  File "/Users/zawwarnaseer/Downloads/youtube_history-master/youtube_history.py", line 373, in <module>
    analysis.run()
  File "/Users/zawwarnaseer/Downloads/youtube_history-master/youtube_history.py", line 352, in run
    self.download_data()
  File "/Users/zawwarnaseer/Downloads/youtube_history-master/youtube_history.py", line 153, in download_data
    raise ValueError(f'"{watch_history}" is not a file. Did you download your YouTube data? ')
ValueError: "YouTube_and_YouTube_Music/history/watch-history.html/YouTube and YouTube Music/history/watch-history.html" is not a file. Did you download your YouTube data? `

This is the error message I keep getting. I originally thought I might have been pointing to the wrong file but I moved my watch-history.html file directly to downloads and tried that but I got the same thing. Any help you could provide or ideas about what I might have done wrong would be much appreciated.

**Comment by kairusds** [comment]
Have you tried changing the path on the `--takeout` flag?

**Comment by Lawlez** [comment]
The file is expected to be in this exact path: YouTube and YouTube Music/history/watch-history.html so when running the tool you need to specify the location of "YouTube and YouTube Music" folder and not the html file directly.
