### ISSUE TITLE
Error when running script

### ISSUE THREAD

**Issue by jasontucker** [Jessime/youtube_history#5]
After running the script for the first time I get this error:

$ python youtube_history.py
Welcome!
Traceback (most recent call last):
  File "youtube_history.py", line 297, in <module>
    analysis.run()
  File "youtube_history.py", line 287, in run
    self.start_analysis()
  File "youtube_history.py", line 273, in start_analysis
    self.check_df()
  File "youtube_history.py", line 185, in check_df
    self.tags = pickle.load(open(os.path.join(self.ran, 'tags.txt'), 'rb'))
IOError: [Errno 2] No such file or directory: 'data/ran/tags.txt'

**Comment by Jessime** [comment]
Interesting; haven't run into that one before. Have you poked around at all to see either:

1. Does `tags.txt` exists in another location in the `youtube_history` folder?
2. Do the `data` and `ran` folders exist?
